source 'git@github.com:serhii-londar/CrowdinSpecs.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

target 'CrowdinSDK_Example' do
  pod 'CrowdinSDK', :path => '../'
  
  pod 'CrowdinScreenshots', :path => '../'
  pod 'CrowdinIntervalUpdates', :path => '../'
  pod 'CrowdinRealtimeUpdates', :path => '../'
  pod 'CrowdinSettings', :path => '../'
  
  pod 'SwiftLint'
  pod 'FileBrowser', :git => 'https://github.com/serhii-londar/FileBrowser.git'
  pod 'FAPanels'
  pod 'R.swift'
end
